#!/bin/sh
sed -i '' '/^Co-[Aa]uthored-[Bb]y:.*[Cc]laude/d' "$1"
sed -i '' '/^Co-[Aa]uthored-[Bb]y:.*[Cc]opilot/d' "$1"
sed -i '' '/^Co-[Aa]uthored-[Bb]y:.*[Cc]ursor/d' "$1"
sed -i '' '/^Made-with:.*[Cc]ursor/d' "$1"
